### ISSUE TITLE
which model card is used?

### ISSUE THREAD

**Issue by Crane-YU** [TEXTurePaper/TEXTurePaper#11]
Hi @TEXTurePaper ,
thx for sharing this great work. However, I was wondering which model card selected from sd-concepts-library is used in your work? Or which images you use to train your own cocept embedding?

**Comment by Crane-YU** [comment]
> HI @Crane-YU There seems to be a bit of a misunderstanding. I guess you are mentioning people in the list of Contributors, but I'm not an author of the paper, but just a contributor who opened a PR to this repo to add a link to a demo on HF Hub. My understanding is that the authors of the paper have to stay anonymous due to the submission policy and they are using this @TEXTurePaper account for it. So, I think the one who you'd like to mention is actually @TEXTurePaper .

just modified. Thank you for mentioning.

**Comment by eladrich** [comment]
Thanks for your interest! We trained our own models using either the standard sets of images used in other papers or dedicated sets of images we captured / rendered. Is there any specific set you are interested in?

**Comment by Crane-YU** [comment]
Hi @eladrich can you share the concept tokens you learn from textures from both the images and mesh models?

**Comment by eladrich** [comment]
Hi, we won't share them all as they are rather big, we do TI  +dreambooth so all model parameters are changed. If there are specific ones you find interesting we might upload them somewhere
