### ISSUE TITLE
Textureless base mesh

### ISSUE THREAD

**Issue by Crane-YU** [TEXTurePaper/TEXTurePaper#17]
Hi @galmetzer, is it ok for you to share all the base mesh that you've used in your work?

**Comment by JulianKnodt** [comment]
I believe most of them are from ModelNet40, according to the paper. I haven't located the exact ones used in the paper, but maybe would help.

**Comment by eladrich** [comment]
Hi,
in the paper's acknowledgments you can find the credit list for all the meshes used throughout the paper
