### ISSUE TITLE
UNet2DConditionModel causing RuntimeError

### ISSUE THREAD

**Issue by BenediktBeigang** [TEXTurePaper/TEXTurePaper#18]
I would like to run your code to demonstrate the results at a presentation. Unfortunately, in the `stable_diffusion_depth.py` file, I get a RuntimeError on line `60` when calling the method:
`UNet2DConditionModel.from_pretrained("stabilityai/stable-diffusion-2-inpainting", subfolder="unet", use_auth_token=self.token).to(self.device)`

> Error: 
> RuntimeError: CUDA has run out of memory. Attempting to allocate 86.00 MiB (GPU 0; 8.00 GiB total capacity; 7.19 GiB already allocated; 0 bytes free; 7.31 GiB total reserved by PyTorch) If reserved memory >> allocated memory, try setting max_split_size_mb to avoid fragmentation.  See documentation for memory management and PYTORCH_CUDA_ALLOC_CONF.

I tried to set `PYTORCH_CUDA_ALLOC_CONF` to the minimum of `21` and also adjust `batch-size`. Unfortunately this did not work. I use a `RTX-3060-Ti`. What hardware did you run your code on? Do you know a way to solve this problem?

I used:
CUDA 11.6
Python3.8.10
pytorch 1.12.1
torchvision 0.13.1
kaolin 0.11.0

**Comment by eladrich** [comment]
See #10
