### ISSUE TITLE
Can I change huggingface yoken to my own sd path

### ISSUE THREAD

**Issue by ChangYaQi** [TEXTurePaper/TEXTurePaper#19]
I want to use my local running sd-webui-1111 version to generate texture for 3d model. Could I just change the model path?

**Comment by yanjk3** [comment]
I have tried it. 
I created ./stabilityai and manually downloaded the "stable-diffusion-2-depth" and "stable-diffusion-2-inpainting" on the hugging face website. 
It works, however, I got many warning messages like "keys mismatch" between the downloaded model checkpoints and the built models. And I got very bad results when running the demo, such as:
![b86d6571461af096eea44d64039651c](https://github.com/TEXTurePaper/TEXTurePaper/assets/48338375/141d9049-8959-4780-b71e-8771df2ab7a8)

I am interested in what results you can get if you download the hugging face checkpoint locally.

**Comment by yanjk3** [comment]
The back view is like:
![image](https://github.com/TEXTurePaper/TEXTurePaper/assets/48338375/67aaf5dc-357b-41c7-8aa4-29703381c05f)

**Comment by yanjk3** [comment]
Well, now I have fixed the problem.....
I find that I used the wrong checkpoint before thus it outputs the "key mismatch" warning. Now it works well. I think you can use your local SD model and just simply replace the pre-trained model path will work.
