### ISSUE TITLE
Code release for Texture Transfer from Images 

### ISSUE THREAD

**Issue by claragarciamoll** [TEXTurePaper/TEXTurePaper#23]
First, we want to congratulate you on your excellent work.

We are currently working on 3D scene virtualization of indoor scenes. To do so, first, we reconstruct a 3D real scene using BundleFusion method. Then, we use O-CNN method for extracting semantic segmentation information used to estimate the Layout of the scene. In parallel, we extract the semantic instances using Mask3D method. Currently, we are working on pose estimation and CAD retrieval. To perform this part, we are exploring ScanNotate method and different improvements to be applied to that. Finally, to complete the full pipeline, we want to incorporate a method to obtain the texture of each object precisely once the CAD models are aligned to the real scene.
To carry out this last step, your method caught up our attention due to the performance shown. However, during our pipeline, we have obtained the RGB images, thus we are interested in using as input 2D images instead of text.

We open this issue in order to know if you have planned to publish the code for texture transfer from images.

**Comment by XiangyuSu611** [comment]
Hi, I have same question. 

We open this issue in order to know if you have planned to publish the code for texture transfer from images.

**Comment by eladrich** [comment]
Code is released in #32
