### ISSUE TITLE
Why is the UV map texture scattered?

### ISSUE THREAD

**Issue by aplatyps** [TEXTurePaper/TEXTurePaper#24]
Is the scattered UV mapping caused by xatlas flawed unwrapping or due to preset viewpoints causing some regions to be occluded? I do notice that the scattering becomes much worse in spherical or irregular geometries. However, it doesn't make sense an object with fairly regular geometry such as a chair to have scattered UV map (see chair example below)? Can someone help me to understand? Thanks.

![chair](https://github.com/TEXTurePaper/TEXTurePaper/assets/103926799/c0591bd0-9d79-4a8c-bd86-71e46ccd4e88)

**Comment by JulianKnodt** [comment]
This is due to Xatlas. If you experiment with xatlas, it will produce a significant number of small charts, especially if the mesh has many small details.
