### ISSUE TITLE
UV base object usage

### ISSUE THREAD

**Issue by felipeiop** [TEXTurePaper/TEXTurePaper#25]
I'm getting a good result overall, however my base obj already has uvs, is there a way to use those original UVs, even if this is creating new ones, how can I get the .obj with the UVS created to match the end result texture?, at the end I have the texture on disk, but can't really use it since it doesn't match the obj UV layout, or I can't find any new obj with uvs unwrapped as the final image.

**Comment by JulianKnodt** [comment]
![image](https://github.com/TEXTurePaper/TEXTurePaper/assets/7675847/dfc212ad-4351-4734-94a8-15db04b018a1)

On line 273: change it to `if False:`
