### ISSUE TITLE
texture consistency

### ISSUE THREAD

**Issue by YuzhiChen001** [TEXTurePaper/TEXTurePaper#27]
thank you for doing a great job！
I'm a little confused about the consistency between multiple perspectives.
Specifically, how can the next perspective ensure that the texture is consistent with the previous one? Is it just through the inpaint function of diffusion to make the newly generated part consistent with the partial texture? Also,  seeds can keep the style consistent.
Are there any other measures to ensure texture consistency?
For example, I want to texture a cup with flower carvings. Can the flower be generated consistently at different viewing angles?
Thanks！

**Comment by eladrich** [comment]
Thanks @YuzhiChen001 

You are mostly correct, consistency comes mainly from the fact that our method runs iteratively with overlapping views and our trimap partitioning allows us to define how and when the overlapping regions should get updated. 

This might result in seams for complex textures, you might find it interesting to look at the more recent [TexFusion](https://research.nvidia.com/labs/toronto-ai/texfusion/) which enforces consistency directly during the diffusion process.

**Comment by YuzhiChen001** [comment]
Thank you for your answers and generous sharing！
