### ISSUE TITLE
Question about tri-map 

### ISSUE THREAD

**Issue by byungjinku** [TEXTurePaper/TEXTurePaper#29]
Hello 

you said the rendering process is divided in tri-map 'keep', 'refine', 'generate' but how do you know the each area of image those 3 area ? i didn't understand your paper 

Best regard

**Comment by eladrich** [comment]
The areas are not known in advance but rather are calculated during optimization based on the current view.

 If you find it hard to fully understand it from the paper, one thing I can suggest is to run the code in debug mode and actually see when these calculations are made.
