### ISSUE TITLE
How to get the vt.pth and ft.pth file?

### ISSUE THREAD

**Issue by muximuxi** [TEXTurePaper/TEXTurePaper#33]
Thank  you for your great work! 
when I run the demo ,python -m scripts.run_texture --config_path=configs/text_guided/napoleon.yaml
get the error: and I cant find the  vt.pth and ft.pth, how can I get this?
File "TEXTurePaper/src/models/textured_mesh.py", line 271, in init_texture_map
logger.info(f'running xatlas to unwrap UVs for mesh: v={v_np.shape} f={f_np.shape}')
UnboundLocalError: local variable 'v_np' referenced before assignment.

**Comment by eladrich** [comment]
Oops, this was a bug with one of my recent commits. Pull the project again and it should work

**Comment by muximuxi** [comment]
> Oops, this was a bug with one of my recent commits. Pull the project again and it should work

I still haven't found it， did you upload any files?

**Comment by muximuxi** [comment]
> Files sould get created when you first run the code, they are not part of the repo

ok, I see .thank you
