### ISSUE TITLE
model checkpoint did  not match

### ISSUE THREAD

**Issue by muximuxi** [TEXTurePaper/TEXTurePaper#34]
when I run the demo, and download the model, get this problem:  and I have checked the model
running cached UV maps from cache/napoleon/vt.pth
2023-10-31 03:11:52 Loaded Mesh, #parameters: 6337536
2023-10-31 03:11:52 TexturedMeshModel()
2023-10-31 03:11:52 loaded hugging face access token from ./TOKEN!
2023-10-31 03:11:52 loading stable diffusion with /TEXTurePaper/stable-diffusion-2-depth...
.....
- This IS expected if you are initializing AutoencoderKL from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AutoencoderKL from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of AutoencoderKL were not initialized from the model checkpoint at /TEXTurePaper/stable-diffusion-2-depth and are newly initialized because the shapes did not match:
- encoder.conv_in.weight: found shape torch.Size([128, 3, 3, 3]) in the checkpoint and torch.Size([64, 3, 3, 3]) in the model instantiated
- encoder.conv_in.bias: found shape torch.Size([128]) in the checkpoint and torch.Size([64]) in the model instantiated

**Comment by eladrich** [comment]
I would guess this is related to some configuration change in diffusers, try checking out whether downgrading to the versions we used (diffusers==0.14.0, transformers==4.27.4). If it doesn't help I'll take a closer look

**Comment by muximuxi** [comment]
my conda envs diffusers==0.14.0, transformers==4.27.4, cuda verison is 11.8 ,and the kaolin=0.14.0, the vae and Unet still have this problem , can not match the size:
vae:
ValueError: Trying to set a tensor of shape torch.Size([128, 3, 3, 3]) in "weight" (which has shape torch.Size([64, 3, 3, 3])), this look incorrect.
Unet:
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "/envs/texture/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 579, in from_pretrained
    set_module_tensor_to_device(
  File "/envs/texture/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([320, 5, 3, 3]) in "weight" (which has shape torch.Size([320, 4, 3, 3])), this look incorrect.

**Comment by eladrich** [comment]
Hmm, can you verify whether that happens with the old version of the repo? This will help me pinpoint the problem
https://github.com/TEXTurePaper/TEXTurePaper/tree/c35e1be0fe4dfe88b89e2203c1440068e0a7d0eb

**Comment by muximuxi** [comment]
I did this on RTX 3090, got the same problem

**Comment by muximuxi** [comment]
It seems I've located the problem， I download the model and loaded it , but there‘s no config.json file in the [stabilityai/stable-diffusion-2-depth] , and there's a model_index.json in it , I changed this name as config.json, and when I loaded vae and Unet without this config.json ,these two model will be loaded correctly. but in project , config.json is required. could you tell me how can I get this file please?
