### ISSUE TITLE
Which software should i use to generate obj files if i want to use own obj files?

### ISSUE THREAD

**Issue by Jacky-MYQ** [TEXTurePaper/TEXTurePaper#35]
Hi!
What an excellent project!!
I want to use my obj files to generate a texture. So i use Blender to build a obj file but i found that it has a mistake saying that _Index array expected to be Nx3_ when i ran run_texture.py .
And i found that the data structure of the obj file generated by Blender is inconsistent with  the Napoleon.obj from Three D Scans.
And i want to know which software should i need to use to generate an useful obj file !

**Comment by eladrich** [comment]
Try to export as `.obj` from blender with the `Triangulated Mesh` option checked
