### ISSUE TITLE
The results are impressive, but problems exist.

### ISSUE THREAD

**Issue by bluestyle97** [TEXTurePaper/TEXTurePaper#4]
Hi, thanks for your excellent work! I have got some impressive results with your method. However, I find that the results are not always satisfactory when using some prompts.  For example, *"a camouflage off-road vehicle"* (the window is not correctly generated):

https://user-images.githubusercontent.com/20635237/217236165-171484f3-6d23-4714-bb49-3592b29b9d10.mp4

And I failed to reproduce *"A desktop Apple iMac"* on the project page:

https://user-images.githubusercontent.com/20635237/217237236-19dbb96c-5917-45f1-9c27-23c1a8245c5e.mp4

Compared to the result on the project page, my result shows significant artifacts. Besides, the result of *"An iPhone 11 pro max"* failed to distinguish the front and back views:

https://user-images.githubusercontent.com/20635237/217238041-4daa9a7f-1ed1-417d-88e1-5bf22e5e5493.mp4

Do you have any suggestions for alleviating the artifacts and improving the multi-view consistency? What parameters can I tune for this goal? I believe this work can facilitate a wide range of real applications.

**Comment by NiluK** [comment]
Generally this is because of UV Mapping problems. Xatlas is decent but it's not perfect. Need to figure out how to AI UV Unwrap, that is a much more tougher problem to solve.
