### ISSUE TITLE
I ran this code <"python -m scripts.finetune_diffusion --pretrained_model_name_........"> with 24GB GPU3090 , it had a mistake "RuntimeError: CUDA out of memory"

### ISSUE THREAD

**Issue by Jacky-MYQ** [TEXTurePaper/TEXTurePaper#42]
I want to konw  whether this code needs more memories or I actually have some mistakes in somewhere else?

**Comment by muximuxi** [comment]
Does this project support multiple GPUs?@eladrich

**Comment by eladrich** [comment]
We do not support multi-gpu train/inference. To reduce memory consumption I would try to take a look at recommend solutions from the diffusers repo.

**Comment by muximuxi** [comment]
How much GPU memory is needed when finetune_diffusion ? @eladrich
