### ISSUE TITLE
Training part of TEXTure

### ISSUE THREAD

**Issue by ChenFengYe** [TEXTurePaper/TEXTurePaper#5]
Hi, thanks for your work.
The idea of trimap is quite impressive！
After reading your paper, it seems you do not train a new model for texturing.
The results are generated by depth-to-image（stable diffusion v2）and inpainting model, which seem not used in the current version of the code.

However, I find the trainer in your code. I am quite confused about this trainer.  Do I misunderstand your approach?
https://github.com/TEXTurePaper/TEXTurePaper/blob/3b4a98a496c1256ad3f6cd7a005d063f8f5ea6bd/src/training/trainer.py#L26

**Comment by eladrich** [comment]
Thanks @ChenFengYe for your kind feedback!
You did understand our approach correctly 💪. Trainer is just not a very good notation here, just something that was left behind from a previous iteration where we were training (see latent-paint).
