### ISSUE TITLE
Not loading any obj files

### ISSUE THREAD

**Issue by krazyjakee** [TEXTurePaper/TEXTurePaper#6]
Whatever obj files I use, it shows this infinitely...

![image](https://user-images.githubusercontent.com/623463/218329706-121397b9-a00a-49e5-805e-cce323b4455d.png)

What are the actual requirements of the obj file for it to work in the demo?

**Comment by eladrich** [comment]
Is that something you are still encountering? Does it also happen for the meshes we provide? One possible problem is that the obj should be a triangular mesh
