### ISSUE TITLE
With UV map?

### ISSUE THREAD

**Issue by mshooter** [TEXTurePaper/TEXTurePaper#9]
Hi, would it be possible to add an obj that does include uv-map?

**Comment by eladrich** [comment]
Yeah, if the .obj file contains a uv-map it should also be loaded.
We only [calculate a uv-map using xatlas](https://github.com/TEXTurePaper/TEXTurePaper/blob/c35e1be0fe4dfe88b89e2203c1440068e0a7d0eb/src/models/textured_mesh.py#L253) if no existing uv-map was found.
